# Generated by Django 4.2.6 on 2023-10-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer360', '0002_customer_social_media_alter_interaction_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='channel',
            field=models.CharField(choices=[('phone', 'Phone'), ('sms', 'SMS'), ('email', 'Email'), ('letter', 'Letter'), ('social_media', 'Social Media')], max_length=15),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10),
        ),
    ]
